### ISSUE TITLE
dateCreated and lastUpdated not working according to GORM

### ISSUE THREAD

**Issue by tanay1212** [micronaut-projects/micronaut-groovy#11]
Here is my domain Which i  have created.This works fine with previous version micronaut.

class User  {
    int id
    String name
    String email
    String password
    Date dateCreated
    Date lastUpdated
}

**UserService Code**-

@Service(User)
class UserService {

      @Transactional
    void create() {
        User user = new User(name:"tanay",email:"p@gmail.com",password:"test".md5())
        user.save(flush: true)
        println("Hello")

    }
}

When i am executing the microanut application  it produces following error-

{"message":"Internal Server Error: Hibernate operation: could not execute statement; SQL [n/a]; Column 'date_created' cannot be null; nested exception is java.sql.SQLIntegrityConstraintViolationException: Column 'date_created' cannot be null"}

**Comment by hakanernam** [comment]
This happened to me as well today. Tried with Mysql and H2 using both Date and java.time.LocalDateTime, same result.

Micronaut Version: 1.1.0
JVM Version: 1.8.0_201
macOS 10.14.4 


**Demo repo:**
https://github.com/hakanernam/mn-groovy-gorm-date_created_issue11.git

**Result:**
$ curl  http://localhost:8080/book
{"message":"Internal Server Error: Hibernate operation: could not execute statement; SQL [n/a]; NULL not allowed for column \"DATE_CREATED\"; SQL statement:\ninsert into book (id, version, date_created, name) values (null, ?, ?, ?) [23502-196]; nested exception is org.h2.jdbc.JdbcSQLException: NULL not allowed for column \"DATE_CREATED\"; SQL statement:\ninsert into book (id, version, date_created, name) values (null, ?, ?, ?) [23502-196]"}

**Comment by tanay1212** [comment]
Yes it works fine with previous versions.I think it is version specific.

**Comment by graemerocher** [comment]
Please try 1.1.1

**Comment by hakanernam** [comment]
Seems resolved, thanks

**Comment by tanay1212** [comment]
Thanks! It's working.
