### ISSUE TITLE
By default id is replicating with existing id's in MYSQL 8.0

### ISSUE THREAD

**Issue by tanay1212** [micronaut-projects/micronaut-groovy#12]
In the latest version 1.1.1 it gives duplicate primary key error when i try to insert a new record in database.It inserts at that id  which already exists in database.I have migrated some data through mysql workbench.It worked fine with previous versions.But creating issue with latest version of micronaut.It produces following error:-

 **{"message":"Internal Server Error: could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"}**

**Comment by jeffbrown** [comment]
Are you using GORM, Micronaut Data, or something else?

**Comment by tanay1212** [comment]
GORM

**Comment by jameskleeh** [comment]
@tanay1212 Please upload a sample application that reproduces the issue
