### ISSUE TITLE
cannot compile application.groovy in Grails

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-groovy#16]
if there is a closure assignment in `application.groovy` file then a static compilation exception is thrown:

for example, following piece of configuration will case the following error:

```
grails.gorm.default.mapping = {
    version false
}
```

```
2019-11-04 14:30:11.826 ERROR --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed
> :bootRun
io.micronaut.context.exceptions.ConfigurationException: Exception occurred reading configuration [application]: startup failed:
Script1.groovy: 8: [Static type checking] - Cannot find matching method Script1#version(boolean). Please check if the declared type is correct and if the method exists.
```

The only possible workaround I was able to move the definitions into methods annotated with `@CompileDynamic`, e.g. 

```
@groovy.transform.CompileDynamic
private static Closure defaultMapping() {
    return {
        version false
    }
}
```

**Comment by jeffbrown** [comment]
> if there is a closure assignment in application.groovy file then a static compilation exception is thrown

I don't think that is necessarily true.  I think it depends on what is happening in the closure.  The samples cited above include DSL code that isn't compatible with static compilation but closures in general work fine in `application.groovy`.

**Comment by jeffbrown** [comment]
> The same applies for GStrings:

I expect that the problem isn't really with GStrings.  I expect the problem is with referencing properties that are not available in the script.  Is it correct that if you wrote code that references the same variables that your GString is referencing that you would see a similar error?

**Comment by musketyr** [comment]
### Closure
Yes, of course, if you have for example just plain empty closure `{ }` then no exception is thrown. But 

### GStrings
Right, the issue was that I couldn't use the `appName` properties.
