### ISSUE TITLE
GORM + tests = slow

### ISSUE THREAD

**Issue by jamesdh** [micronaut-projects/micronaut-groovy#200]
Locally I added a Spring StopWatch to the HibernateDatastoreFactory bean to measure the amount of time spent: 

- Scanning for Entity classes
- Initializing HibernateDatastore
- Building/registering/injecting remaining beans 

Turns out initializing HIbernateDatastore consumed ~99% of the stopwatch on average,  which on my quad-core/32gb MacBook Pro comes out to ~3 seconds. 

~3 seconds added on to every test spec means tests now take **much** longer to run overall compared to their runtime within Grails. 

I understand one of the core purposes of Micronaut is to avoid runtime reflection, scanning, etc, and that the speed increases that gives you when you work within those boundaries allows for us to simply restart the ApplicationContext for every spec. But it would be fantastic if, for the sake of projects/teams that are still reliant on GORM and all of its runtime slowness, there was some way to work around recreating the ApplicationContext/HibernateDatastore on every test spec, specifically when using GORM. 

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Expected Behaviour

Test run in rapid succession

### Actual Behaviour

3+ second pause between every test spec

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.3.3
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
This should be better for Micronaut 3 since entities will not need to be scanned on the classpath

**Comment by jameskleeh** [comment]
Beyond this any further improvements would have to be done in the gorm repo, so the issue should be filed there

**Comment by jamesdh** [comment]
@jameskleeh awesome, looking forward to giving 3.0.0 a spin then!
