### ISSUE TITLE
MongoDB + GORM + Groovy: No GORM implementations configured

### ISSUE THREAD

**Issue by DontPlayTheGame** [micronaut-projects/micronaut-groovy#265]
### Expected Behavior

I am not sure if I just don't see something or if this is a bug.

Two applications, same code:
- https://github.com/DontPlayTheGame/example-mn2513-grom-mongo 
- https://github.com/DontPlayTheGame/example-mn301-grom-mongo

With  the micronaut 2.5.13 application, executing the GET and POST requests works as expected
(see https://github.com/DontPlayTheGame/example-mn2513-grom-mongo/tree/main/src/test/groovy/org/example/user) 
I get the users and can insert users

### Actual Behaviour

The micronaut 3.0.1 application with the most recent dependencies  return always an error:
```
	"errors": [
	  {
		"message": "Internal Server Error: No GORM implementations configured. Ensure GORM has been initialized correctly"
	  }
	]

```

I have tried so many things ... so at the end I just reduced everything to the linked examples. 
Do i miss something very basic or is this a bug?

### Environment Information

Windows 10
OpenJDK 11.0.2
Micronaut 3.0.1 / 3.0.2
micronaut-mongo-gorm:3.0.0

### Example Application

https://github.com/DontPlayTheGame/example-mn301-grom-mongo
https://github.com/DontPlayTheGame/example-mn2513-grom-mongo

### Version

3.0.x

**Comment by sjrd218** [comment]
I had to manually add `@Introspected` to my classes annotated with `@Entity` before they got picked up by the gorm configuration processor. Don't know if that's a new requirement or a bug.

**Comment by sdelamo** [comment]
GORM is not supported since Micronaut Framework 4.
