### ISSUE TITLE
one-to-many error

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-groovy#3]
when use one-two-many
there is  no Session (through reference chain:  error

demo in
https://github.com/micronaut-zysoft/micronaut-database-authentication-provider-groovy

https://github.com/micronaut-zysoft/micronaut-database-authentication-provider-groovy/blob/master/complete/src/main/groovy/example/micronaut/controller/BookControoler.groovy

**Comment by ibmsoft** [comment]
demo in
https://github.com/micronaut-zysoft/micronaut-database-authentication-provider-groovy

**Comment by graemerocher** [comment]
You should load all the data necessary to return from the controller. Lazy loading is not supported.

**Comment by ibmsoft** [comment]
i use the 
         static mapping = {
        book lazy: false
    }
has the same problem

**Comment by volnei** [comment]
@ibmsoft 

Try using 

```
static mapping = {
    book fetch: 'join'
}
```
