### ISSUE TITLE
Groovy 4 Support

### ISSUE THREAD

**Issue by codeconsole** [micronaut-projects/micronaut-groovy#322]
### Groovy 4 is now GA
4.0.1 
https://groovy.apache.org/download.html

Any plans on supporting it?  Considering the package renaming, what would be a realistic timeline to see Groovy 4 introduced?

**Comment by sdelamo** [comment]
@codeconsole we will target support of Groovy 4 with Micronaut 4

**Comment by timyates** [comment]
As a reminder to myself, this gradle may be of use with the migration (as Groovy has finally changed groupId with v4)

```
configurations {
    all*.exclude group: "org.codehaus.groovy", module: "groovy-bom"
}

dependencies {
    api platform("org.apache.groovy:groovy-bom:$groovyVersion")
}
```

**Comment by wetted** [comment]
This can also be useful in places if `org.codehaus.groovy` leaks into a build (java project with spock tests).

```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("org.codehaus.groovy:groovy"))
                .using(module("org.apache.groovy:groovy:4.0.5"))
    }
}
```

**Comment by sdelamo** [comment]
Close via https://github.com/micronaut-projects/micronaut-groovy/commit/b3d02a4f8329327fea6c2d287fdda88f8d8674d4  and https://github.com/micronaut-projects/micronaut-groovy/commit/8aa94898aa056614506ffbef98455e36af87a746
