### ISSUE TITLE
domain         id generator: "uuid"

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-groovy#5]
in my domain 
set 
 static mapping = {
        id generator: "uuid"
    }
 
HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead

**Comment by baqlawi** [comment]
I'm facing the same issue with Grails 5.3.6. How did you solve the issue?
