### ISSUE TITLE
Upgrade to GORM 7.0.5 once it is released

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-groovy#55]
It includes bug fixes in `grails-data-store-core` related to: https://github.com/micronaut-projects/micronaut-groovy/issues/48

Latest stable for :
[grails-datastore-gorm-hibernate5](https://mvnrepository.com/artifact/org.grails/grails-datastore-gorm-hibernate5) is set to 7.0.3

however 

[grails-datastore-core](https://mvnrepository.com/artifact/org.grails/grails-datastore-core) is set to 7.0.4

Could you take care of this @puneetbehl ?

**Comment by sdelamo** [comment]
build has been updated to 7.1. Thus, this no longer applies.

**Comment by anu-devco** [comment]
Does this fixes deprecation warning "org.hibernate.Criteria API is deprecated"

I was in assuming once GORM is 7 is implementated those warnings would go away but I still see them in my application after upgrading Micronaut to 2.4.2 from Micronaut 1.1.2.

I don't know what horrors are waiting for me with upgrade but this deprecation is the first thing I noticed.
