### ISSUE TITLE
Upgrade groovy micronaut apps to use groovy 3.x by default

### ISSUE THREAD

**Issue by deandelponte** [micronaut-projects/micronaut-groovy#70]
### Steps to reproduce

1. Modify your terminal to use Micronaut-2.0.0.M3 on the command line
2. Create a new app.  For example, run `mn create-app bean-bug --lang=groovy`

### Expected Results:
I would expect the generated app to use the latest version of groovy which, at the time of this writing is version 3.0.4

### Actual Results
groovy version 2.5.10 is the default

### Environment Information

- **Operating System**: macOS Catalina version 10.15.5
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** Corretto-11.0.7.10.1 (build 11.0.7+10-LTS)

**Comment by graemerocher** [comment]
Can't reproduce this with master
